openapi: 3.0.3
info:
  title: API sqlLite3
  version: 1.0.0
  description: API предназначена для работы добавления, получения записей с базы данных
paths:
  /api/addCompletedWork:
    post:
      operationId: api_addCompletedWork_create
      parameters:
      - in: query
        name: idPracticalWork
        schema:
          type: integer
        required: true
      - in: query
        name: idStudent
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/addPracticalWork:
    post:
      operationId: api_addPracticalWork_create
      parameters:
      - in: query
        name: subject
        schema:
          type: string
        required: true
      - in: query
        name: title
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/addStudent:
    post:
      operationId: api_addStudent_create
      parameters:
      - in: query
        name: course
        schema:
          type: integer
        required: true
      - in: query
        name: fullName
        schema:
          type: string
        required: true
      - in: query
        name: group
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/getCompletedWork:
    get:
      operationId: api_getCompletedWork_retrieve
      parameters:
      - in: query
        name: idStudent
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/getPracticalWork:
    get:
      operationId: api_getPracticalWork_retrieve
      parameters:
      - in: query
        name: subject
        schema:
          type: string
        required: true
      - in: query
        name: title
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/getStudent:
    get:
      operationId: api_getStudent_retrieve
      parameters:
      - in: query
        name: course
        schema:
          type: integer
        required: true
      - in: query
        name: fullName
        schema:
          type: string
        required: true
      - in: query
        name: group
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
