name: Deploy

on:
  push:
    branches:
      - "master"
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone master branch
        run: git clone https://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@github.com/DaniilMpala/agregator_Backend.git --branch master --single-branch /output
      # Setup key
      - name: Setup key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.SSH }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      - name: Deploy in server
        run: > 
          cd /output &&
          rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@84.252.74.161:/var/www/discountsite &&
          docker stop $(docker ps -a -q) &&
          docker system prune -a -f && 
          cd /discountsite &&
          docker build -t django . &&
          docker run -d -p 8000:8000 django

